print("first code")
x=int(input('Enter x'))
y=int(input('enter y'))
print('diff :',x-y)
print ('sum :',x+y)
print('pro :',x*y)
print('div :',x/y),
print('floor :',x//y)
print('mod :',x%y)
print('power :',x**y)
print('bit and :',x&y)
print('bit or :',x|y)
print('bit not :',~x)
print('bit xor :',x^y)
print('left shift :',x<<y)
print('rt shift :',x>>y)
print('logical and :',x and y)
print('logical or :',x or y)
print('logical not :',not x)
print('not = :',x != y)
print('==:',x==y)
print('les than :',x<y)
print('> :',x>y)
print('>= :',x>=y)
print('<= :',x<=y)
